# Generated by Django 4.1.7 on 2023-08-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Создан', 'created'), ('Принят', 'pass'), ('В сборке', 'collect'), ('В пути', 'in way'), ('Доставлен', 'delivery'), ('Закрыт', 'closed')], default='Cоздан', max_length=255, null=True),
        ),
    ]
